version: "3.8"

services:
  frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    environment:
      BACKEND_HOSTNAME: ${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: ghcr.io/shuffle/shuffle-backend:latest
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps:z
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files:z
    env_file: .env
    environment:
      SHUFFLE_APP_HOTLOAD_FOLDER: /shuffle-apps
      SHUFFLE_FILE_LOCATION: /shuffle-files
    restart: unless-stopped

  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      ENVIRONMENT_NAME: Shuffle
      ORG_ID: Shuffle
      BASE_URL: http://${OUTER_HOSTNAME}:5001
      DOCKER_API_VERSION: 1.40
      SHUFFLE_STATS_DISABLED: true
      SHUFFLE_LOGS_DISABLED: true
      SHUFFLE_SWARM_CONFIG: run
      SHUFFLE_WORKER_IMAGE: ghcr.io/shuffle/shuffle-worker:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    hostname: shuffle-opensearch
    container_name: shuffle-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - shuffle
    volumes:
      - shuffle-database:/usr/share/opensearch/data:z
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  shuffle:
    driver: bridge

volumes:
  shuffle-database:
