
name: helm

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - "charts/**"

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https -y --no-install-recommends
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y --no-install-recommends

      - name: Update helm dependencies
        run: helm dependency update ./charts/shuffle

      - name: Package Helm chart
        run: helm package ./charts/shuffle --destination ./charts

      - name: Login to OCI registry (ghcr.io)
        run: helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push helm chart
        run: helm push ./charts/shuffle-*.tgz oci://ghcr.io/shuffle/shuffle/charts
