name: Upload App SDK to PiPy

on:
  workflow_dispatch:  # Allows the workflow to be run manually from GitHub
    inputs:
      version:
        description: 'Version of the package to publish'
        required: true
  release:
    types: [published]
  push:
    tags:
      - 'v*'  # Triggers when a version tag is pushed (e.g., v1.0.0)


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
      working-directory: ./backend/app_sdk
        
    - name: Build package
      run: python -m build
      working-directory: ./backend/app_sdk
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.10.2
      with:
        verify-metadata: false
        repository-url: https://upload.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      env:
        ACTIONS_STEP_DEBUG: true  # Enables debug mode for this step
      working-directory: ./backend/app_sdk

